### ISSUE TITLE
#US02 Como usuario quiero una sección para poder registrar mis datos.

### ISSUE THREAD

**Issue by Alejo11Lucero** [FrancoGL/ISPC-FullStack#2]
Maquetar pagina de registro.

**Comment by FrancoGL** [comment]
Una persona se encarga del HTML y la otra del CSS, yo dejaré un orden que pueden o no seguir, la decisión final es de quienes fueron asignados al issue.
@GabrielSucaria → HTML 
@Lukill22  → CSS
