### ISSUE TITLE
#US03 Como usuario quiero sección para iniciar sesión.

### ISSUE THREAD

**Issue by Alejo11Lucero** [FrancoGL/ISPC-FullStack#3]
Maquetar login.

**Comment by FrancoGL** [comment]
Una persona se encarga del HTML y la otra del CSS, yo dejaré un orden que pueden o no seguir, la decisión final es de quienes fueron asignados al issue.
@pri1593 → HTML
@veroivk → CSS

**Comment by veroivk** [comment]
Reasignación de HTML y CSS a @veroivk

**Comment by FrancoGL** [comment]
En el link a figma se encuentra un borrador de un login
